language: java
jdk: 
  - openjdk8
sudo: true
services:
  - docker
before_install:
  - docker pull postgres:latest
  - docker pull mysql:latest
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
